In [2]:
import numpy as np

# Without filter

In [8]:
v_ac_input = 7.34
loads_1 = np.array([2172, 3846, 9860])
inp_current = np.array([2.88, 1.65, 0.64])/1000
v_ac_1 = np.array([2.963, 3.009, 3.013])
v_dc_1 = np.array([5.46, 5.57, 5.65])

v_rms = np.sqrt(np.power(v_ac_1,2) + np.power(v_dc_1,2))
v_max = v_rms*np.sqrt(2)
two_v_max_by_pi = 2*v_max/(np.pi)
r_factor_1 = v_ac_1/v_dc_1
efficiency_1 = (np.power(v_dc_1, 2)*100/loads_1)/(v_ac_input*inp_current)
v_dc_1, two_v_max_by_pi, r_factor_1, efficiency_1

(array([5.46, 5.57, 5.65]),
 array([5.5929117 , 5.69971915, 5.76488426]),
 array([0.54267399, 0.54021544, 0.53327434]),
 array([64.92873129, 66.6071891 , 68.91979021]))

In [4]:
np.mean(r_factor_1), np.mean(efficiency_1)

(0.538721256271184, 66.81857019959408)

### Error Analysis

In [8]:
delta_r = np.sqrt(np.power((0.001/v_ac_1), 2) + np.power((0.01/v_dc_1), 2))
delta_r_mean = np.sqrt(np.sum(np.power(delta_r, 2)))/3

delta_r, delta_r_mean

(array([0.00186234, 0.00182583, 0.00180076]), 0.001056446264015296)

In [12]:
delta_eta = np.sqrt(np.power((0.001/v_ac_1), 2) + np.power((0.02/v_dc_1), 2) + np.power((0.01/v_ac_input), 2) + np.power((1/loads_1), 2))
delta_eta_mean = np.sqrt(np.sum(np.power(delta_r, 2)))/3

delta_eta, delta_eta_mean*100

(array([0.00394963, 0.00386355, 0.00380879]), 0.10564462640152959)

# With filter

In [4]:
c_1 = 23.05e-6
vac_1 = np.array([0.422, 0.252, 0.103])
vdc_1 = np.array([8.42, 8.69, 9.05])
ripple_factor_1 = vac_1/vdc_1

c_2 = 10.4e-6
vac_2 = np.array([0.816, 0.514, 0.224])
vdc_2 = np.array([7.94, 8.39, 8.96])
ripple_factor_2 = vac_2/vdc_2

c_3 = 23.50e-6
vac_3 = np.array([0.897, 1.205, 1.581])
vdc_3 = np.array([8.46, 7.95, 7.26])

c_3 = 37.47e-6
vac_3 = np.array([0.307, 0.181, 0.074])
vdc_3 = np.array([8.59, 8.81, 9.10])
ripple_factor_3 = vac_3/vdc_3

ripple_factor_1, ripple_factor_2, ripple_factor_3

(array([0.05011876, 0.02899885, 0.01138122]),
 array([0.10277078, 0.06126341, 0.025     ]),
 array([0.03573923, 0.02054484, 0.00813187]))