In [1]:
import numpy as np

# Without filter

In [12]:
v_ac_input = 7.56
loads_1 = np.array([2200, 1000, 1500])
inp_current = np.array([1.78, 3.91, 2.63])/1000
v_ac_1 = np.array([3.868, 3.860, 3.874])
v_dc_1 = np.array([3.127, 3.110, 3.128])

v_rms = np.sqrt(np.power(v_ac_1,2) + np.power(v_dc_1,2))
v_max = v_rms*2
v_max_by_pi = v_max/(np.pi)
r_factor_1 = v_ac_1/v_dc_1
efficiency_1 = (np.power(v_dc_1, 2)*100/loads_1)/(v_ac_input*inp_current)
v_dc_1, v_max_by_pi, r_factor_1, efficiency_1

(array([3.127, 3.11 , 3.128]),
 array([3.16647488, 3.15571464, 3.16984613]),
 array([1.23696834, 1.24115756, 1.23849105]),
 array([33.02868506, 32.72067281, 32.80686154]))

In [13]:
np.mean(r_factor_1), np.mean(efficiency_1)

(1.238872315041893, 32.85207313677853)

# With filter

In [8]:
loads_2 = np.array([2200, 1500, 1000])

c_1 = 10.71e-6
vac_1 = np.array([1.563, 1.971, 2.420])
vdc_1 = np.array([7.29, 6.52, 5.73])
ripple_factor_1 = vac_1/vdc_1

c_2 = 28.83e-6
vac_2 = np.array([0.832, 1.097, 1.475])
vdc_2 = np.array([8.44, 7.84, 7.31])
ripple_factor_2 = vac_2/vdc_2

c_3 = 23.50e-6
vac_3 = np.array([0.897, 1.205, 1.581])
vdc_3 = np.array([8.46, 7.95, 7.26])
ripple_factor_3 = vac_3/vdc_3

c_4 = 37.99e-6
vac_4 = np.array([0.651, 0.882, 1.188])
vdc_4 = np.array([8.85, 8.40, 7.81])
ripple_factor_4 = vac_4/vdc_4

ripple_factor_1, ripple_factor_2, ripple_factor_3, ripple_factor_4

(array([0.21440329, 0.30230061, 0.42233857]),
 array([0.0985782 , 0.13992347, 0.20177839]),
 array([0.10602837, 0.15157233, 0.2177686 ]),
 array([0.07355932, 0.105     , 0.15211268]))